export const SITE_NAME = "OPTCG API"

export const COLORS = ["Red", "Blue", "Green", "Purple", "Yellow", "Black"]

export const COSTS = [1, 2, 3, 4, 5, 6, 7, 8, 9].map(String)

export const POWERS = [
  1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 11000, 12000,
].map(String)

export const COUNTERS = [1000, 2000].map(String)

export const CARD_TYPES = ["CHARACTER", "EVENT", "LEADER", "STAGE"]

export const RARITIES = ["C", "L", "P", "R", "SEC", "SP CARD", "SR", "TR", "UC"]

export const CARD_SETS = [
  "Tournament Pack Vol.6",
  "Tournament Pack Vol.3",
  "-EMPERORS IN THE NEW WORLD- [OP-09]",
  "ONE PIECE FILM edition [ST-05]",
  "-Purple Monkey.D.Luffy- [ST-18]",
  "Included in Event Pack Vol.2",
  "-Monkey D. Luffy-[ST-08]",
  "Winner prize for Sealed Battle 2023 Vol.1",
  "Pirates Party Vol.4",
  "Pre-Release OP06",
  "One Piece Card Game x PSA Exclusive Promo Card",
  "Tournament Pack Vol.1",
  "-The Three Brothers-[ST13]",
  "Offline Regional Finalist Card Set 2024 Vol. 3",
  "Winner Pack 2025 Vol.2",
  "-WINGS OF THE CAPTAIN-[OP06]",
  "-Animal Kingdom Pirates-[ST-04]",
  "-AWAKENING OF THE NEW ERA-[OP05]",
  "-ROMANCE DAWN- [OP01]NotesErrata Card",
  "Offline Regional Participation Pack 2024 Vol. 2",
  "-ROMANCE DAWN- [OP01]",
  "Treasure Cup August – September",
  "-The Three Captains-[ST-10]",
  "Pirates Party Vol.3",
  "Offline Regional Participation Pack 2025 Vol.1",
  "Included in Online Regional Participation Pack Vol.1",
  "Special Goods Set -Ace/Sabo/Luffy-",
  "GIFT COLLECTION 2023 [GC-01]",
  "Regional 2024 wave2",
  "Treasure Cup February 2025",
  "-Straw Hat Crew-[ST-01]NotesErrata Card",
  "-Yamato-[ST-09]",
  "-The Seven Warlords of the Sea-[ST-03]NotesErrata Card",
  "ST15-20 Release Event",
  "Included in Pirates Party Card Vol.2",
  "-PARAMOUNT WAR- [OP02]",
  "Tournament Pack Vol.5",
  "Pirates Party Vol.7",
  "-ONE PIECE CARD THE BEST- [PRB-01]",
  "Regionals Wave 3",
  "Offline Regional Participation Pack 2024 Vol. 1",
  "Tournament Pack Vol.7",
  "Event Pack Vol.3",
  "-KINGDOMS OF INTRIGUE- [OP04]",
  "-PARAMOUNT WAR- [OP02]NotesErrata Card",
  "-Zoro & Sanji- [ST-12]",
  "Anime Expo 2023",
  "Store Treasure Cup August – September 2024",
  "-Animal Kingdom Pirates-[ST-04]NotesErrata Card",
  "Tournament Pack Vol.2",
  "-Green Uta- [ST-16]",
  "Pre-Release OP02",
  "Premium Card Collection -25th Edition-",
  "-Straw Hat Crew-[ST-01]",
  "-ROMANCE DAWN- [OP01]NotesErrata CardErrata Card",
  "Dreamhack Dallas 2024",
  "Tournament Pack 2024 Oct.-Dec.",
  "Event Pack Vol.6",
  "Pre-Release OP04",
  "-PARAMOUNT WAR- [OP02]NotesBanned Card",
  "-PILLARS OF STRENGTH- [OP03]NotesErrata Card",
  "Premium Card Collection -FILM RED Edition-",
  "Included in Promotion Pack 2022",
  "-AWAKENING OF THE NEW ERA-[OP05]NotesErrata Card",
  "Included in Event Pack Vol.1",
  "-Worst Generation-[ST-02]",
  "-Red Edward.Newgate- [ST-15]",
  "Offline Regional Participation Pack 2024 Vol. 3",
  "2025 NEW YEAR EVENT",
  "Regional 2024 wave1",
  "Event Pack Vol.5",
  "English Version 1st Anniversary Set",
  "-Uta-[ST-11]",
  "-500 YEARS IN THE FUTURE- [OP-07]",
  "Super Pre-Release",
  "-Animal Kingdom Pirates-[ST-04]NotesErrata CardErrata Card",
  "Pre-Release OP08",
  "-Blue Donquixote Doflamingo- [ST-17]",
  "Pirates Party Vol.6",
  "ST-11 Uta Deck Battle Participation Pack",
  "Sealed Battle 2023 Vol.1",
  "-Black Smoker- [ST-19]",
  "Pre-Release OP03",
  "-Worst Generation-[ST-02]NotesErrata Card",
  "ONE PIECE DAY Dallas -Card Game Celebration-",
  "-PILLARS OF STRENGTH- [OP03]",
  "-Memorial Collection- [EB-01]",
  "Japanese 1st Anniversary Set",
  "Big Mom Pirates [ST-07]",
  "Included in FILM RED Promotion Card Set",
  "Pirates Party Vol.5",
  "Treasure Cup November-December",
  "-Yellow Charlotte Katakuri- [ST-20]",
  "Sealed Battle Kit Vol.1",
  "Included in Pirates Party Card Vol.1",
  "Tournament Pack Vol.4",
  "-Absolute Justice- [ST-06]",
  "-3D2Y- [ST-14]",
  "-TWO LEGENDS- [OP-08]",
  "Tournament Kit 2025 Vol.2",
  "-The Seven Warlords of the Sea-[ST-03]",
]

export const CARD_CLASSES = [
  "Alabasta",
  "Alabasta/Straw Hat Crew",
  "Amazon Lily",
  "Animal",
  "Animal Kingdom Pirates",
  "Animal Kingdom Pirates/Former CP9",
  "Animal Kingdom Pirates/Hawkins Pirates",
  "Animal Kingdom Pirates/On-Air Pirates",
  "Animal Kingdom Pirates/Smile",
  "Animal/Alabasta",
  "Animal/Alabasta/Straw Hat Crew",
  "Animal/Baroque Works",
  "Animal/Blackbeard Pirates",
  "Animal/CP0",
  "Animal/Cross Guild",
  "Animal/Drum Kingdom",
  "Animal/Drum Kingdom/Straw Hat Crew",
  "Animal/East Blue",
  "Animal/Egghead/Straw Hat Crew",
  "Animal/Foxy Pirates",
  "Animal/Impel Down",
  "Animal/Jaya/Sky Island",
  "Animal/Kuja Pirates",
  "Animal/Land of Wano",
  "Animal/Muggy Kingdom",
  "Animal/Red-Haired Pirates",
  "Animal/Sky Island",
  "Animal/Straw Hat Crew",
  "Animal/Water Seven",
  "Baroque Works",
  "Bellamy Pirates",
  "Big Mom Pirates",
  "Big Mom Pirates/Homies",
  "Biological Weapon/Navy",
  "Biological Weapon/Punk Hazard",
  "Blackbeard Pirates",
  "Bowin Island",
  "Buggy Pirates",
  "CP0",
  "CP6",
  "CP7",
  "CP9",
  "Celestial Dragons",
  "Cross Guild",
  "Cross Guild/Former Baroque Works",
  "Donquixote Pirates",
  "Donquixote Pirates/Punk Hazard",
  "Dressrosa",
  "Dressrosa/Barto Club",
  "Dressrosa/Beautiful Pirates",
  "Dressrosa/Happosui Army",
  "Dressrosa/Heart Pirates",
  "Dressrosa/Revolutionary Army",
  "Dressrosa/Straw Hat Crew",
  "Dressrosa/Yonta Maria Fleet",
  "Drum Kingdom",
  "Drum Kingdom/Straw Hat Crew",
  "East Blue",
  "East Blue/Alvida Pirates",
  "East Blue/Arlong Pirates",
  "East Blue/Black Cat Pirates",
  "East Blue/Buggy Pirates",
  "East Blue/Former Navy",
  "East Blue/Krieg Pirates",
  "East Blue/Straw Hat Crew",
  "Egghead",
  "Egghead/Bonney Pirates",
  "Egghead/Seraphim",
  "Egghead/Straw Hat Crew",
  "FILM",
  "FILM/Animal/Golden Lion Pirates",
  "FILM/Animal/Straw Hat Crew",
  "FILM/Asuka Island",
  "FILM/Big Mom Pirates",
  "FILM/CP0",
  "FILM/Crown Island",
  "FILM/Drum Kingdom",
  "FILM/Eldoraggo Crew",
  "FILM/Fish-Man/Straw Hat Crew",
  "FILM/Former Navy/Gasparde Pirates",
  "FILM/Golden Lion Pirates",
  "FILM/Grantesoro",
  "FILM/Jellyfish Pirates",
  "FILM/Mecha Island",
  "FILM/Minks/Heart Pirates",
  "FILM/Mugiwara Chase",
  "FILM/Navy",
  "FILM/Neo Navy",
  "FILM/Omatsuri Island",
  "FILM/Red-Haired Pirates",
  "FILM/Revolutionary Army",
  "FILM/Scientist/Golden Lion Pirates",
  "FILM/Shipbuilding Town",
  "FILM/Straw Hat Crew",
  "FILM/Supernovas/Barto Club",
  "FILM/Supernovas/Heart Pirates",
  "FILM/Supernovas/Straw Hat Crew",
  "FILM/The Four Emperors/Red-Haired Pirates",
  "FILM/The Pirates Fest",
  "FILM/Trump Pirates",
  "Firetank Pirates",
  "Fish-Man",
  "Fish-Man Island",
  "Fish-Man/Arlong Pirates",
  "Fish-Man/East Blue/Arlong Pirates",
  "Fish-Man/Egghead/Straw Hat Crew",
  "Fish-Man/Flying Pirates",
  "Fish-Man/Former Arlong Pirates",
  "Fish-Man/Foxy Pirates",
  "Fish-Man/Impel Down",
  "Fish-Man/Land of Wano/The Akazaya Nine",
  "Fish-Man/Merfolk/New Fish-Man Pirates",
  "Fish-Man/New Fish-Man Pirates",
  "Fish-Man/Revolutionary Army",
  "Fish-Man/Straw Hat Crew",
  "Fish-Man/The Seven Warlords of the Sea/The Sun Pirates",
  "Fish-Man/The Sun Pirates",
  "Fish-Man/Water Seven",
  "Fish-Man/Whitebeard Pirates",
  "Foolshout Island",
  "Former Baroque Works",
  "Former Navy",
  "Former Rocks Pirates",
  "Former Rocks Pirates/Animal Kingdom Pirates",
  "Former Rocks Pirates/Big Mom Pirates",
  "Former Roger Pirates",
  "Former Rumbar Pirates",
  "Former Whitebeard Pirates",
  "Foxy Pirates",
  "Frost Moon Village",
  "Giant/Animal Kingdom Pirates",
  "Giant/Dressrosa/New Giant Pirates",
  "Giant/Fish-Man/Foxy Pirates",
  "Giant/Navy",
  "Giant/New Giant Pirates",
  "Giant/Revolutionary Army",
  "Giant/Thriller Bark Pirates",
  "Giant/Whitebeard Pirates Allies",
  "Giant/World Government",
  "Goa Kingdom",
  "Goa Kingdom/Bluejam Pirates",
  "Gyro Pirates",
  "Happosui Army",
  "Heart Pirates",
  "Impel Down",
  "Impel Down/Buggy Pirates",
  "Impel Down/Former Baroque Works",
  "Impel Down/Jailer Beast",
  "Impel Down/Revolutionary Army",
  "Impel Down/Straw Hat Crew",
  "Impel Down/The Seven Warlords of the Sea/Kuja Pirates",
  "Jaya/Botanist",
  "Jaya/Monkey Mountain Alliance",
  "Jaya/Sky Island/Shandian Warrior",
  "Journalist",
  "Kid Pirates",
  "King of the Pirates/Roger Pirates",
  "Kingdom of GERMA",
  "Kingdom of GERMA/The Vinsmoke Family",
  "Kingdom of Prodence/Dressrosa",
  "Krieg Pirates",
  "Kuja Pirates",
  "Land of Wano",
  "Land of Wano/Animal Kingdom Pirates",
  "Land of Wano/Former Whitebeard Pirates",
  "Land of Wano/Kouzuki Clan",
  "Land of Wano/Kurozumi Clan",
  "Land of Wano/Straw Hat Crew",
  "Land of Wano/The Akazaya Nine",
  "Land of Wano/The Four Emperors/Big Mom Pirates",
  "Land of Wano/Thriller Bark Pirates",
  "Land of Wano/Whitebeard Pirates",
  "Long Ring Long Land",
  "Lulucia Kingdom",
  "Lunarian/Animal Kingdom Pirates",
  "Mary Geoise",
  "Merfolk",
  "Merfolk/The Sun Pirates",
  "Merfolk/Water Seven",
  "Minks",
  "Minks/Big Mom Pirates",
  "Minks/Heart Pirates",
  "Minks/Land of Wano/The Akazaya Nine",
  "Minks/Revolutionary Army",
  "Minks/The Akazaya Nine",
  "Monkey Mountain Alliance",
  "Mountain Bandits",
  "Muggy Kingdom/Thriller Bark Pirates",
  "Music/FILM",
  "Navy",
  "Navy/Donquixote Pirates",
  "Navy/Donquixote Pirates/Punk Hazard",
  "Navy/Drake Pirates/Animal Kingdom Pirates",
  "Navy/Supernovas/Drake Pirates",
  "ODYSSEY",
  "ODYSSEY/Animal/Straw Hat Crew",
  "ODYSSEY/CP9",
  "ODYSSEY/Navy",
  "ODYSSEY/Navy/Donquixote Pirates",
  "ODYSSEY/Revolutionary Army",
  "ODYSSEY/Straw Hat Crew",
  "ODYSSEY/Supernovas/Heart Pirates",
  "ODYSSEY/Supernovas/Straw Hat Crew",
  "ODYSSEY/The Seven Warlords of the Sea/Baroque Works",
  "ODYSSEY/The Seven Warlords of the Sea/Donquixote Pirates",
  "ODYSSEY/Whitebeard Pirates",
  "Ohara",
  "Ohara/Giant/Navy",
  "Peachbeard Pirates/Blackbeard Pirates Allies",
  "Plague/Animal Kingdom Pirates",
  "Punk Hazard",
  "Punk Hazard/Straw Hat Crew",
  "Red-Haired Pirates",
  "Revolutionary Army",
  "Roger Pirates",
  "Rumbar Pirates",
  "Scientist",
  "Scientist/Egghead",
  "Scientist/Punk Hazard",
  "Sky Island",
  "Sky Island/Shandian Warrior",
  "Sky Island/Vassals",
  "Sniper Island",
  "Spade Pirates",
  "Straw Hat Crew",
  "Supernovas/Barto Club",
  "Supernovas/Beautiful Pirates",
  "Supernovas/Bonney Pirates",
  "Supernovas/Caribou Pirates",
  "Supernovas/Fallen Monk Pirates",
  "Supernovas/Firetank Pirates",
  "Supernovas/Hawkins Pirates",
  "Supernovas/Heart Pirates",
  "Supernovas/Kid Pirates",
  "Supernovas/Kid Pirates/SMILE",
  "Supernovas/Navy/Drake Pirates",
  "Supernovas/On-Air Pirates",
  "Supernovas/Straw Hat Crew",
  "The Flying Fish Riders",
  "The Four Emperors/Animal Kingdom Pirates",
  "The Four Emperors/Animal Kingdom Pirates/Big Mom Pirates",
  "The Four Emperors/Big Mom Pirates",
  "The Four Emperors/Blackbeard Pirates",
  "The Four Emperors/Cross Guild",
  "The Four Emperors/Egghead/Straw Hat Crew",
  "The Four Emperors/Land of Wano",
  "The Four Emperors/Red-Haired Pirates",
  "The Four Emperors/Straw Hat Crew",
  "The Four Emperors/Whitebeard Pirates",
  "The House of Lambs",
  "The Moon",
  "The Seven Warlords of the Sea",
  "The Seven Warlords of the Sea/Baroque Works",
  "The Seven Warlords of the Sea/Blackbeard Pirates",
  "The Seven Warlords of the Sea/Buggy's Delivery",
  "The Seven Warlords of the Sea/Donquixote Pirates",
  "The Seven Warlords of the Sea/Heart Pirates",
  "The Seven Warlords of the Sea/Kuja Pirates",
  "The Seven Warlords of the Sea/Muggy Kingdom",
  "The Seven Warlords of the Sea/Revolutionary Army",
  "The Seven Warlords of the Sea/Thriller Bark Pirates",
  "The Tontattas/Dressrosa",
  "The Vinsmoke Family",
  "The Vinsmoke Family/GERMA 66",
  "The Vinsmoke Family/Kingdom of GERMA",
  "Thriller Bark Pirates",
  "Thriller Bark Pirates/Former Rocks Pirates",
  "Water Seven",
  "Water Seven/Galley-La Company",
  "Water Seven/Navy",
  "Water Seven/Straw Hat Crew",
  "Water Seven/The Franky Family",
  "Weevil's Mother",
  "Whitebeard Pirates",
  "Whitebeard Pirates Allies",
  "Whole Cake Island",
  "Windmill Village",
  "World Government",
  "World Pirates",
  "音楽/FILM",
]
